server:
  port: 8080

spring:
  application:
    name: user
#  profiles:
#    active: dev # 环境
  cloud:
    nacos:
      server-addr: localhost:8848
      config:
        namespace: f46302e3-f087-47a2-83a0-4b0484d5367b
        group: dev
      discovery:
        namespace: f46302e3-f087-47a2-83a0-4b0484d5367b
        group: kon
#        cluster-name: SKT
  config:
    import:
      - optional:nacos:user-dev.yaml

#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/lc_user?useUnicode=true&characterEncoding=UTF-8
#    username: root
#    password: 123456
#spring:
#  cloud:
#    loadbalancer:
#      nacos:
#        enabled: true
#logging:
#  level:
#    com.dwg: debug