server:
  port: 8080

spring:
  application:
    name: user
  profiles:
    active: dev # 环境
  cloud:
    nacos:
      server-addr: localhost:8848
#      config:
#        file-extension: yaml          # 文件后缀名
#        server-addr: localhost:8848
#      discovery:
#        namespace: f46302e3-f087-47a2-83a0-4b0484d5367b
#        cluster-name: SKT
  config:
    import:
      - optional:nacos:user.yaml

#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/lc_user?useUnicode=true&characterEncoding=UTF-8
#    username: root
#    password: 123456
#spring:
#  cloud:
#    loadbalancer:
#      nacos:
#        enabled: true
#logging:
#  level:
#    com.dwg: debug