server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lc_user?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
  cloud:
    loadbalancer:
      nacos:
        enabled: true
logging:
  level:
    com.dwg: debug