server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lc_order?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
  cloud:
    loadbalancer:
      nacos:
        enabled: true
feign:
  httpclient:
    enabled: true # 支持HttpClient的开关
    max-connections: 200 # 最大连接数
    max-connections-per-route: 50 # 单个路径的最大连接数
#  client:
#    config:
#      default:
#        logger-level: full
logging:
  level:
    com.dwg: debug
