server:
  port: 10010
logging:
  level:
    com.dwg: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos地址
    gateway:
      routes:
        - id: user            # 路由唯一标识
          uri: lb://user      # 路由的目标地址,lb表示负载均衡
          predicates:         # 判断请求是否符合规则
            - Path=/user/**   # 路径断言,判断路径是否以/user开头
        - id: order
          uri: lb://order
          predicates:
            - Path=/order/**

